#!/usr/bin/env python3
"""Preview icon variants (font codepoint vs text fallback) without ANSI."""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agent_icons import PUA_LOGOS, TEXT_LOGOS, font_available  # noqa: E402

AGENT_NAMES = {
    "claude": "Claude",
    "codex": "Codex",
    "opencode": "OpenCode",
    "omp": "OMP",
    "cline": "Cline",
    "mastracode": "MastraCode",
    "kimi": "Kimi",
    "kilo": "Kilo",
    "maki": "Maki",
    "pi": "Pi",
    "hermes": "Hermes",
    "cursor": "Cursor",
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--select", choices=("auto", "font", "text", "none"))
    parser.add_argument("--config", type=Path)
    args = parser.parse_args()

    print(f"Custom font detected: {'yes' if font_available() else 'no'}\n")
    print(f"{'Agent':<12} {'Font (PUA)':<14} {'Text fallback'}")
    for agent, name in AGENT_NAMES.items():
        glyph = PUA_LOGOS[agent]
        print(f"{name:<12} {glyph} U+{ord(glyph):04X}      {TEXT_LOGOS[agent]}")

    if args.select:
        config_path = args.config
        if config_path is None:
            config_dir = os.environ.get("HERDR_PLUGIN_CONFIG_DIR")
            if not config_dir:
                print("--config is required outside a plugin invocation", file=sys.stderr)
                return 1
            config_path = Path(config_dir) / "config.toml"
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(
            f'# Generated by preview.py\nvariant = "{args.select}"\n', encoding="ascii"
        )
        print(f"\nSelected {args.select}; wrote {config_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
